-- FLO-108: isolated PostgreSQL schema for the AI video production control plane.
--
-- Rules:
--   * IDs are generated by the application (UUID v4/v7); no extension required.
--   * Approved/referenced revisions are insert-only. The application repository
--     never UPDATEs revision payloads; changes create a child revision.
--   * Large media stays in content-addressed storage. PostgreSQL stores hashes,
--     metadata, dependencies, approvals, and business state.
--   * Temporal owns durable execution history. PostgreSQL owns queryable product
--     truth and an outbox for integration events.

CREATE SCHEMA IF NOT EXISTS video_pipeline;
SET search_path TO video_pipeline, public;

CREATE TABLE series (
    id                  UUID PRIMARY KEY,
    schema_version      TEXT NOT NULL DEFAULT 'v1',
    title               TEXT NOT NULL,
    status              TEXT NOT NULL CHECK (status IN ('DRAFT', 'ACTIVE', 'ARCHIVED')),
    default_profile_id  UUID,
    rights_declaration  JSONB NOT NULL,
    created_by          TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE source_revisions (
    id               UUID PRIMARY KEY,
    series_id        UUID NOT NULL REFERENCES series(id),
    revision         INTEGER NOT NULL CHECK (revision > 0),
    parent_revision_id UUID REFERENCES source_revisions(id),
    status           TEXT NOT NULL CHECK (status IN ('DRAFT', 'APPROVED', 'ARCHIVED', 'DISABLED')),
    content_hash     CHAR(64) NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    artifact_uri     TEXT NOT NULL CHECK (artifact_uri LIKE 'cas://sha256/%'),
    language         TEXT NOT NULL,
    rights_snapshot  JSONB NOT NULL,
    created_by       TEXT NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (series_id, revision),
    UNIQUE (series_id, content_hash)
);

CREATE TABLE evidence_spans (
    id                  UUID PRIMARY KEY,
    source_revision_id  UUID NOT NULL REFERENCES source_revisions(id),
    chapter_ref         TEXT,
    start_offset        BIGINT NOT NULL CHECK (start_offset >= 0),
    end_offset          BIGINT NOT NULL CHECK (end_offset > start_offset),
    excerpt_hash        CHAR(64) NOT NULL CHECK (excerpt_hash ~ '^[0-9a-f]{64}$'),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE episodes (
    id           UUID PRIMARY KEY,
    series_id    UUID NOT NULL REFERENCES series(id),
    ordinal      INTEGER NOT NULL CHECK (ordinal > 0),
    title        TEXT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (series_id, ordinal)
);

CREATE TABLE episode_revisions (
    id                  UUID PRIMARY KEY,
    episode_id          UUID NOT NULL REFERENCES episodes(id),
    revision            INTEGER NOT NULL CHECK (revision > 0),
    parent_revision_id  UUID REFERENCES episode_revisions(id),
    status              TEXT NOT NULL CHECK (status IN ('DRAFT', 'G1_APPROVED', 'G2_APPROVED', 'G3_LOCKED', 'ARCHIVED')),
    target_duration_ms  INTEGER NOT NULL CHECK (target_duration_ms > 0),
    content_hash        CHAR(64) NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    created_by          TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (episode_id, revision),
    UNIQUE (episode_id, content_hash)
);

CREATE TABLE scenes (
    id          UUID PRIMARY KEY,
    episode_id  UUID NOT NULL REFERENCES episodes(id),
    ordinal     INTEGER NOT NULL CHECK (ordinal > 0),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (episode_id, ordinal)
);

CREATE TABLE scene_revisions (
    id                  UUID PRIMARY KEY,
    scene_id            UUID NOT NULL REFERENCES scenes(id),
    episode_revision_id UUID NOT NULL REFERENCES episode_revisions(id),
    revision            INTEGER NOT NULL CHECK (revision > 0),
    parent_revision_id  UUID REFERENCES scene_revisions(id),
    status              TEXT NOT NULL CHECK (status IN ('DRAFT', 'APPROVED', 'ARCHIVED')),
    content_hash        CHAR(64) NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    payload             JSONB NOT NULL,
    created_by          TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (scene_id, revision)
);

CREATE TABLE shots (
    id          UUID PRIMARY KEY,
    scene_id    UUID NOT NULL REFERENCES scenes(id),
    ordinal     INTEGER NOT NULL CHECK (ordinal > 0),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (scene_id, ordinal)
);

CREATE TABLE entity_revisions (
    id                  UUID PRIMARY KEY,
    series_id           UUID NOT NULL REFERENCES series(id),
    entity_id           UUID NOT NULL,
    entity_type         TEXT NOT NULL CHECK (entity_type IN ('WORLD', 'CHARACTER', 'RELATIONSHIP', 'LOCATION', 'PROP')),
    revision            INTEGER NOT NULL CHECK (revision > 0),
    parent_revision_id  UUID REFERENCES entity_revisions(id),
    status              TEXT NOT NULL CHECK (status IN ('DRAFT', 'APPROVED', 'ARCHIVED', 'DISABLED')),
    schema_version      TEXT NOT NULL,
    payload             JSONB NOT NULL,
    evidence_ids        UUID[] NOT NULL DEFAULT '{}',
    adaptation_added    BOOLEAN NOT NULL DEFAULT false,
    content_hash        CHAR(64) NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    created_by          TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (entity_id, revision)
);

CREATE TABLE context_revisions (
    id                  UUID PRIMARY KEY,
    series_id           UUID NOT NULL REFERENCES series(id),
    scope_type          TEXT NOT NULL CHECK (scope_type IN ('SERIES', 'EPISODE', 'SCENE', 'SHOT')),
    scope_id            UUID NOT NULL,
    revision            INTEGER NOT NULL CHECK (revision > 0),
    parent_revision_id  UUID REFERENCES context_revisions(id),
    status              TEXT NOT NULL CHECK (status IN ('DRAFT', 'APPROVED', 'ARCHIVED', 'DISABLED')),
    schema_version      TEXT NOT NULL,
    resolver_version    TEXT NOT NULL,
    payload             JSONB NOT NULL,
    content_hash        CHAR(64) NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    created_by          TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (scope_type, scope_id, revision)
);

CREATE TABLE license_snapshots (
    id                  UUID PRIMARY KEY,
    subject_type        TEXT NOT NULL CHECK (subject_type IN ('MODEL', 'WEIGHT', 'LORA', 'NODE', 'ASSET', 'VOICE', 'FONT', 'MUSIC', 'SFX', 'SOURCE')),
    subject_ref         TEXT NOT NULL,
    license_id          TEXT NOT NULL,
    license_hash        CHAR(64) NOT NULL CHECK (license_hash ~ '^[0-9a-f]{64}$'),
    policy_status       TEXT NOT NULL CHECK (policy_status IN ('ALLOWED', 'REQUIRES_REVIEW', 'BLOCKED', 'EXPIRED')),
    territories         TEXT[] NOT NULL DEFAULT '{}',
    commercial_use      BOOLEAN NOT NULL,
    expires_at          TIMESTAMPTZ,
    source_uri          TEXT NOT NULL,
    reviewed_by         TEXT,
    reviewed_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (subject_type, subject_ref, license_hash)
);

CREATE TABLE consent_assets (
    id                  UUID PRIMARY KEY,
    subject_ref         TEXT NOT NULL,
    consent_type        TEXT NOT NULL CHECK (consent_type IN ('VOICE_CLONE', 'LIKENESS', 'TRAINING_DATA')),
    content_hash        CHAR(64) NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    artifact_uri        TEXT NOT NULL CHECK (artifact_uri LIKE 'cas://sha256/%'),
    territories         TEXT[] NOT NULL DEFAULT '{}',
    expires_at          TIMESTAMPTZ,
    status              TEXT NOT NULL CHECK (status IN ('ACTIVE', 'REVOKED', 'EXPIRED')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE provider_profiles (
    id                    UUID PRIMARY KEY,
    provider              TEXT NOT NULL CHECK (provider IN ('MOCK', 'VOLCENGINE', 'CLAUDE_COMPATIBLE', 'GENERIC')),
    display_name          TEXT NOT NULL,
    base_url_ref          TEXT NOT NULL,
    credential_ref        TEXT,
    enabled               BOOLEAN NOT NULL DEFAULT false,
    mode                  TEXT NOT NULL CHECK (mode IN ('MOCK', 'DRY_RUN', 'LIVE')),
    health                TEXT NOT NULL CHECK (health IN ('NOT_CONFIGURED', 'UNKNOWN', 'READY', 'DEGRADED', 'UNAVAILABLE')),
    credential_fingerprint TEXT,
    config_hash           CHAR(64) NOT NULL CHECK (config_hash ~ '^[0-9a-f]{64}$'),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (provider, display_name),
    CHECK (credential_ref IS NULL OR credential_ref !~* '(api[_-]?key|token|secret)=')
);

CREATE TABLE provider_capability_snapshots (
    id                    UUID PRIMARY KEY,
    provider_profile_id   UUID NOT NULL REFERENCES provider_profiles(id),
    capability_alias      TEXT NOT NULL CHECK (capability_alias IN ('text.primary', 'image.primary', 'video.primary', 'speech.primary')),
    model_id              TEXT NOT NULL,
    endpoint_id           TEXT,
    route_version         TEXT NOT NULL,
    supported_inputs      TEXT[] NOT NULL,
    limits                JSONB NOT NULL,
    pricing_rule_version  TEXT,
    capability_hash       CHAR(64) NOT NULL CHECK (capability_hash ~ '^[0-9a-f]{64}$'),
    status                TEXT NOT NULL CHECK (status IN ('DRAFT', 'ACTIVE', 'DEPRECATED', 'UNAVAILABLE')),
    effective_at          TIMESTAMPTZ NOT NULL,
    expires_at            TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (provider_profile_id, capability_alias, capability_hash)
);

CREATE TABLE model_routes (
    id                      UUID PRIMARY KEY,
    capability_alias        TEXT NOT NULL CHECK (capability_alias IN ('text.primary', 'image.primary', 'video.primary', 'speech.primary')),
    route_version           TEXT NOT NULL,
    priority                INTEGER NOT NULL CHECK (priority > 0),
    capability_snapshot_id  UUID NOT NULL REFERENCES provider_capability_snapshots(id),
    status                  TEXT NOT NULL CHECK (status IN ('DRAFT', 'ACTIVE', 'DISABLED')),
    automatic_failover      BOOLEAN NOT NULL DEFAULT false,
    created_by              TEXT NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (capability_alias, route_version, priority)
);

CREATE TABLE generation_profiles (
    id                  UUID PRIMARY KEY,
    profile_id          UUID NOT NULL,
    revision            INTEGER NOT NULL CHECK (revision > 0),
    parent_revision_id  UUID REFERENCES generation_profiles(id),
    schema_version      TEXT NOT NULL,
    status              TEXT NOT NULL CHECK (status IN ('DRAFT', 'VALIDATED', 'ACTIVE', 'DISABLED')),
    stage               TEXT NOT NULL CHECK (stage IN ('M0', 'M1', 'M2', 'M3', 'EXPERIMENT')),
    aspect_profile      TEXT NOT NULL CHECK (aspect_profile IN ('16:9_720P24', '9:16_720P24')),
    episode_target_ms   INTEGER NOT NULL CHECK (episode_target_ms > 0),
    shot_min_ms         INTEGER NOT NULL DEFAULT 4000 CHECK (shot_min_ms >= 1000),
    shot_max_ms         INTEGER NOT NULL DEFAULT 6000 CHECK (shot_max_ms >= shot_min_ms),
    capability_routes   JSONB NOT NULL,
    media_processing    JSONB NOT NULL,
    render_defaults     JSONB NOT NULL,
    qc_thresholds       JSONB NOT NULL,
    retry_policy        JSONB NOT NULL,
    budget_policy       JSONB NOT NULL,
    license_policy      JSONB NOT NULL,
    fallback_profile_id UUID,
    content_hash        CHAR(64) NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    created_by          TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (profile_id, revision),
    UNIQUE (profile_id, content_hash),
    FOREIGN KEY (fallback_profile_id) REFERENCES generation_profiles(id)
);

ALTER TABLE series
    ADD CONSTRAINT fk_series_default_profile
    FOREIGN KEY (default_profile_id) REFERENCES generation_profiles(id);

CREATE TABLE assets (
    id          UUID PRIMARY KEY,
    series_id   UUID NOT NULL REFERENCES series(id),
    asset_type  TEXT NOT NULL CHECK (asset_type IN ('CHARACTER', 'SCENE', 'PROP', 'VOICE', 'FONT', 'MUSIC', 'SFX', 'IMAGE', 'VIDEO', 'AUDIO', 'SUBTITLE', 'WORKFLOW')),
    scope_type  TEXT NOT NULL CHECK (scope_type IN ('SERIES', 'EPISODE', 'SCENE', 'SHOT')),
    scope_id    UUID NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE asset_versions (
    id                    UUID PRIMARY KEY,
    asset_id              UUID NOT NULL REFERENCES assets(id),
    revision              INTEGER NOT NULL CHECK (revision > 0),
    parent_revision_id    UUID REFERENCES asset_versions(id),
    status                TEXT NOT NULL CHECK (status IN ('DRAFT', 'APPROVED', 'ARCHIVED', 'DISABLED')),
    content_hash          CHAR(64) NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    artifact_uri          TEXT NOT NULL CHECK (artifact_uri LIKE 'cas://sha256/%'),
    media_type            TEXT NOT NULL,
    dimensions            JSONB,
    source_ref            TEXT NOT NULL,
    generation_run_id     UUID,
    execution_refs        JSONB NOT NULL DEFAULT '{}',
    license_snapshot_id   UUID NOT NULL REFERENCES license_snapshots(id),
    consent_asset_id      UUID REFERENCES consent_assets(id),
    approval_decision_id  UUID,
    created_by            TEXT NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    archived_at           TIMESTAMPTZ,
    UNIQUE (asset_id, revision),
    UNIQUE (asset_id, content_hash)
);

CREATE TABLE episode_script_revisions (
    id                  UUID PRIMARY KEY,
    episode_id          UUID NOT NULL REFERENCES episodes(id),
    revision            INTEGER NOT NULL CHECK (revision > 0),
    parent_revision_id  UUID REFERENCES episode_script_revisions(id),
    status              TEXT NOT NULL CHECK (status IN ('DRAFT', 'APPROVED', 'ARCHIVED')),
    schema_version      TEXT NOT NULL,
    payload             JSONB NOT NULL,
    evidence_ids        UUID[] NOT NULL DEFAULT '{}',
    content_hash        CHAR(64) NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    created_by          TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (episode_id, revision)
);

CREATE TABLE storyboard_revisions (
    id                  UUID PRIMARY KEY,
    episode_id          UUID NOT NULL REFERENCES episodes(id),
    script_revision_id  UUID NOT NULL REFERENCES episode_script_revisions(id),
    revision            INTEGER NOT NULL CHECK (revision > 0),
    parent_revision_id  UUID REFERENCES storyboard_revisions(id),
    status              TEXT NOT NULL CHECK (status IN ('DRAFT', 'APPROVED', 'ARCHIVED')),
    content_hash        CHAR(64) NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    created_by          TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (episode_id, revision)
);

CREATE TABLE approval_decisions (
    id              UUID PRIMARY KEY,
    series_id       UUID NOT NULL REFERENCES series(id),
    episode_id      UUID REFERENCES episodes(id),
    gate            TEXT NOT NULL CHECK (gate IN ('G1', 'G2', 'Q1', 'G3')),
    decision        TEXT NOT NULL CHECK (decision IN ('APPROVED', 'REJECTED', 'RETURNED')),
    reason_code     TEXT NOT NULL,
    explanation     TEXT,
    actor_id        TEXT NOT NULL,
    actor_role      TEXT NOT NULL,
    decided_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    trace_id        TEXT NOT NULL
);

CREATE TABLE approval_bindings (
    decision_id     UUID NOT NULL REFERENCES approval_decisions(id),
    object_type     TEXT NOT NULL,
    revision_id     UUID NOT NULL,
    content_hash    CHAR(64) NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    PRIMARY KEY (decision_id, object_type, revision_id)
);

ALTER TABLE asset_versions
    ADD CONSTRAINT fk_asset_version_approval
    FOREIGN KEY (approval_decision_id) REFERENCES approval_decisions(id);

CREATE TABLE shot_spec_revisions (
    id                       UUID PRIMARY KEY,
    shot_id                  UUID NOT NULL REFERENCES shots(id),
    storyboard_revision_id   UUID NOT NULL REFERENCES storyboard_revisions(id),
    revision                 INTEGER NOT NULL CHECK (revision > 0),
    parent_revision_id       UUID REFERENCES shot_spec_revisions(id),
    lifecycle_state          TEXT NOT NULL CHECK (lifecycle_state IN ('DRAFT', 'READY', 'QUEUED', 'RUNNING', 'QC_PENDING', 'AUTO_QC_FAILED', 'REVIEW', 'APPROVED', 'CANCELLED')),
    freshness                TEXT NOT NULL CHECK (freshness IN ('FRESH', 'STALE', 'REVALIDATED')),
    duration_ms              INTEGER NOT NULL CHECK (duration_ms > 0),
    aspect_profile           TEXT NOT NULL,
    fps                      INTEGER NOT NULL DEFAULT 24 CHECK (fps > 0),
    width                    INTEGER NOT NULL CHECK (width > 0),
    height                   INTEGER NOT NULL CHECK (height > 0),
    cast_count               INTEGER NOT NULL CHECK (cast_count BETWEEN 0 AND 2),
    primary_action_count     INTEGER NOT NULL CHECK (primary_action_count = 1),
    narrative                JSONB NOT NULL,
    asset_version_refs       UUID[] NOT NULL,
    context_revision_ids     UUID[] NOT NULL,
    effective_context_hash   CHAR(64) NOT NULL CHECK (effective_context_hash ~ '^[0-9a-f]{64}$'),
    continuity               JSONB NOT NULL,
    cinematography           JSONB NOT NULL,
    generation_profile_id    UUID NOT NULL REFERENCES generation_profiles(id),
    gate2_decision_id        UUID NOT NULL REFERENCES approval_decisions(id),
    content_hash             CHAR(64) NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    created_by               TEXT NOT NULL,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (shot_id, revision),
    UNIQUE (shot_id, content_hash)
);

CREATE TABLE effective_context_snapshots (
    id                    UUID PRIMARY KEY,
    shot_spec_revision_id UUID NOT NULL REFERENCES shot_spec_revisions(id),
    schema_version        TEXT NOT NULL,
    resolver_version      TEXT NOT NULL,
    context_revision_ids  UUID[] NOT NULL,
    normalized_payload    JSONB NOT NULL,
    content_hash          CHAR(64) NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (shot_spec_revision_id, content_hash)
);

CREATE TABLE prompt_snapshots (
    id                            UUID PRIMARY KEY,
    shot_spec_revision_id         UUID NOT NULL REFERENCES shot_spec_revisions(id),
    schema_version                TEXT NOT NULL,
    compiler_version              TEXT NOT NULL,
    prompt_template_ref           TEXT NOT NULL,
    effective_context_snapshot_id UUID NOT NULL REFERENCES effective_context_snapshots(id),
    asset_version_refs            UUID[] NOT NULL,
    predecessor_summary           JSONB,
    tail_frame_hash               CHAR(64) CHECK (tail_frame_hash ~ '^[0-9a-f]{64}$'),
    positive_prompt               TEXT NOT NULL,
    negative_prompt               TEXT NOT NULL,
    model_payload                 JSONB NOT NULL,
    evidence_ids                  UUID[] NOT NULL DEFAULT '{}',
    normalized_input_hash         CHAR(64) NOT NULL CHECK (normalized_input_hash ~ '^[0-9a-f]{64}$'),
    content_hash                  CHAR(64) NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (shot_spec_revision_id, content_hash)
);

CREATE TABLE generation_runs (
    id                       UUID PRIMARY KEY,
    shot_spec_revision_id    UUID NOT NULL REFERENCES shot_spec_revisions(id),
    prompt_snapshot_id       UUID NOT NULL REFERENCES prompt_snapshots(id),
    generation_profile_id    UUID NOT NULL REFERENCES generation_profiles(id),
    temporal_workflow_id     TEXT NOT NULL,
    temporal_run_id          TEXT,
    run_spec_digest          CHAR(64) NOT NULL CHECK (run_spec_digest ~ '^[0-9a-f]{64}$'),
    creative_attempt         INTEGER NOT NULL CHECK (creative_attempt > 0),
    state                    TEXT NOT NULL CHECK (state IN ('DRAFT', 'VALIDATED', 'QUEUED', 'RUNNING', 'UNKNOWN', 'RECONCILING', 'REQUIRES_ACTION', 'CANCEL_REQUESTED', 'CANCELLED', 'SUCCEEDED', 'FAILED')),
    failure_class            TEXT CHECK (failure_class IN ('INFRASTRUCTURE', 'TRANSIENT', 'CREATIVE', 'INPUT', 'LICENSE', 'BUDGET', 'AUTHENTICATION', 'PERMISSION', 'QUOTA', 'RATE_LIMIT', 'CONTENT_SAFETY', 'REGION', 'MODEL')),
    failure_code             TEXT,
    fallback_reason          TEXT,
    dry_run                  BOOLEAN NOT NULL DEFAULT false,
    budget_approval_id       TEXT NOT NULL,
    trace_id                 TEXT NOT NULL,
    created_by               TEXT NOT NULL,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at               TIMESTAMPTZ,
    finished_at              TIMESTAMPTZ,
    CHECK ((creative_attempt <= 2) OR (fallback_reason IS NOT NULL))
);

ALTER TABLE asset_versions
    ADD CONSTRAINT fk_asset_version_generation_run
    FOREIGN KEY (generation_run_id) REFERENCES generation_runs(id);

CREATE UNIQUE INDEX ux_generation_runs_active_digest
    ON generation_runs (run_spec_digest)
    WHERE state IN ('VALIDATED', 'QUEUED', 'RUNNING', 'UNKNOWN', 'RECONCILING', 'REQUIRES_ACTION', 'SUCCEEDED');

CREATE TABLE generation_attempts (
    id                 UUID PRIMARY KEY,
    generation_run_id  UUID NOT NULL REFERENCES generation_runs(id),
    sequence           INTEGER NOT NULL CHECK (sequence > 0),
    attempt_kind       TEXT NOT NULL CHECK (attempt_kind IN ('PROVIDER_REQUEST', 'INFRASTRUCTURE_RETRY', 'CREATIVE_REVISION')),
    state              TEXT NOT NULL CHECK (state IN ('VALIDATED', 'QUEUED', 'RUNNING', 'UNKNOWN', 'RECONCILING', 'REQUIRES_ACTION', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    input_hash         CHAR(64) NOT NULL CHECK (input_hash ~ '^[0-9a-f]{64}$'),
    model_snapshot     JSONB NOT NULL,
    parameter_diff     JSONB NOT NULL DEFAULT '{}',
    heartbeat_at       TIMESTAMPTZ,
    started_at         TIMESTAMPTZ,
    finished_at        TIMESTAMPTZ,
    failure_code       TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (generation_run_id, sequence)
);

CREATE TABLE budget_reservations (
    id                    UUID PRIMARY KEY,
    generation_run_id     UUID NOT NULL REFERENCES generation_runs(id),
    amount_minor          BIGINT NOT NULL CHECK (amount_minor >= 0),
    currency              CHAR(3) NOT NULL,
    pricing_rule_version  TEXT NOT NULL,
    estimate_payload      JSONB NOT NULL,
    status                TEXT NOT NULL CHECK (status IN ('PENDING_CONFIRMATION', 'RESERVED', 'SETTLED', 'RELEASED', 'REJECTED')),
    confirmed_by          TEXT,
    confirmed_at          TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (generation_run_id, id)
);

CREATE TABLE provider_jobs (
    id                      UUID PRIMARY KEY,
    generation_attempt_id   UUID NOT NULL REFERENCES generation_attempts(id),
    provider_profile_id     UUID NOT NULL REFERENCES provider_profiles(id),
    capability_snapshot_id  UUID NOT NULL REFERENCES provider_capability_snapshots(id),
    budget_reservation_id   UUID NOT NULL REFERENCES budget_reservations(id),
    idempotency_key         TEXT NOT NULL,
    request_hash            CHAR(64) NOT NULL CHECK (request_hash ~ '^[0-9a-f]{64}$'),
    request_snapshot        JSONB NOT NULL,
    upstream_task_id        TEXT,
    upstream_request_id     TEXT,
    state                   TEXT NOT NULL CHECK (state IN ('DRAFT', 'VALIDATED', 'QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'UNKNOWN', 'REQUIRES_ACTION', 'CANCELLED')),
    progress                INTEGER NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
    retry_count             INTEGER NOT NULL DEFAULT 0 CHECK (retry_count BETWEEN 0 AND 3),
    next_poll_at            TIMESTAMPTZ,
    timeout_at              TIMESTAMPTZ,
    error_code              TEXT,
    error_snapshot          JSONB,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    terminal_at             TIMESTAMPTZ,
    UNIQUE (provider_profile_id, idempotency_key),
    UNIQUE (provider_profile_id, upstream_task_id),
    CHECK (request_snapshot::text !~* '"(authorization|api[_-]?key|access[_-]?token|cookie|signed[_-]?url)"[[:space:]]*:')
);

CREATE TABLE provider_callback_receipts (
    provider_job_id   UUID NOT NULL REFERENCES provider_jobs(id),
    callback_id       TEXT NOT NULL,
    sequence          BIGINT NOT NULL CHECK (sequence > 0),
    payload_hash      CHAR(64) NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    applied           BOOLEAN NOT NULL,
    ignored_reason    TEXT,
    received_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (provider_job_id, callback_id)
);

CREATE TABLE cost_ledger (
    id                    UUID PRIMARY KEY,
    provider_job_id       UUID NOT NULL REFERENCES provider_jobs(id),
    budget_reservation_id UUID NOT NULL REFERENCES budget_reservations(id),
    entry_type            TEXT NOT NULL CHECK (entry_type IN ('ESTIMATE', 'RESERVATION', 'ACTUAL', 'RELEASE', 'ADJUSTMENT')),
    amount_minor          BIGINT,
    currency              CHAR(3),
    units                 NUMERIC(18,6),
    unit_name             TEXT,
    pricing_rule_version  TEXT NOT NULL,
    verified              BOOLEAN NOT NULL DEFAULT false,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE artifacts (
    id            UUID PRIMARY KEY,
    content_hash  CHAR(64) NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    artifact_uri  TEXT NOT NULL CHECK (artifact_uri LIKE 'cas://sha256/%'),
    media_type    TEXT NOT NULL,
    size_bytes    BIGINT NOT NULL CHECK (size_bytes >= 0),
    media_spec    JSONB NOT NULL DEFAULT '{}',
    status        TEXT NOT NULL CHECK (status IN ('ACTIVE', 'ORPHAN_CANDIDATE', 'ARCHIVED', 'DISABLED')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (content_hash)
);

CREATE TABLE run_artifacts (
    generation_run_id UUID NOT NULL REFERENCES generation_runs(id),
    artifact_id       UUID NOT NULL REFERENCES artifacts(id),
    role              TEXT NOT NULL CHECK (role IN ('INPUT', 'OUTPUT', 'TAIL_FRAME', 'PROXY', 'AUDIO', 'SUBTITLE', 'MANIFEST')),
    PRIMARY KEY (generation_run_id, artifact_id, role)
);

CREATE TABLE qc_reports (
    id                 UUID PRIMARY KEY,
    generation_run_id  UUID NOT NULL REFERENCES generation_runs(id),
    threshold_version  TEXT NOT NULL,
    state              TEXT NOT NULL CHECK (state IN ('PASSED', 'FAILED', 'NEEDS_REVIEW')),
    metrics            JSONB NOT NULL,
    reason_codes       TEXT[] NOT NULL DEFAULT '{}',
    report_hash        CHAR(64) NOT NULL CHECK (report_hash ~ '^[0-9a-f]{64}$'),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (generation_run_id, report_hash)
);

CREATE TABLE review_tasks (
    id                 UUID PRIMARY KEY,
    series_id          UUID NOT NULL REFERENCES series(id),
    episode_id         UUID REFERENCES episodes(id),
    shot_id            UUID REFERENCES shots(id),
    generation_run_id  UUID REFERENCES generation_runs(id),
    review_type        TEXT NOT NULL CHECK (review_type IN ('Q1', 'G1', 'G2', 'G3', 'LICENSE', 'BUDGET')),
    state              TEXT NOT NULL CHECK (state IN ('OPEN', 'APPROVED', 'REJECTED', 'CANCELLED')),
    reason_codes       TEXT[] NOT NULL DEFAULT '{}',
    assigned_role      TEXT NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    decided_at         TIMESTAMPTZ
);

CREATE TABLE generation_manifests (
    id                 UUID PRIMARY KEY,
    scope_type         TEXT NOT NULL CHECK (scope_type IN ('SHOT', 'EPISODE')),
    scope_revision_id  UUID NOT NULL,
    schema_version     TEXT NOT NULL,
    payload            JSONB NOT NULL,
    manifest_hash      CHAR(64) NOT NULL CHECK (manifest_hash ~ '^[0-9a-f]{64}$'),
    artifact_id        UUID NOT NULL REFERENCES artifacts(id),
    gate_decision_id   UUID REFERENCES approval_decisions(id),
    locked_at          TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (scope_type, scope_revision_id, manifest_hash)
);

CREATE TABLE revision_dependencies (
    producer_type        TEXT NOT NULL,
    producer_revision_id UUID NOT NULL,
    consumer_type        TEXT NOT NULL,
    consumer_revision_id UUID NOT NULL,
    dependency_role      TEXT NOT NULL,
    producer_hash        CHAR(64) NOT NULL CHECK (producer_hash ~ '^[0-9a-f]{64}$'),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (producer_type, producer_revision_id, consumer_type, consumer_revision_id, dependency_role)
);

CREATE TABLE freshness_impacts (
    id                    UUID PRIMARY KEY,
    source_revision_id    UUID NOT NULL,
    affected_type         TEXT NOT NULL,
    affected_revision_id  UUID NOT NULL,
    state                 TEXT NOT NULL CHECK (state IN ('STALE', 'REVALIDATED', 'REGENERATED')),
    reason_code           TEXT NOT NULL,
    resolution_decision_id UUID REFERENCES approval_decisions(id),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at           TIMESTAMPTZ,
    UNIQUE (source_revision_id, affected_type, affected_revision_id)
);

CREATE TABLE operation_requests (
    id                    UUID PRIMARY KEY,
    operation_type        TEXT NOT NULL,
    aggregate_type        TEXT NOT NULL,
    aggregate_id          UUID NOT NULL,
    expected_revision     INTEGER,
    state                 TEXT NOT NULL CHECK (state IN ('ACCEPTED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCEL_REQUESTED', 'CANCELLED')),
    temporal_workflow_id  TEXT,
    temporal_run_id       TEXT,
    trace_id              TEXT NOT NULL,
    requested_by          TEXT NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE idempotency_records (
    scope               TEXT NOT NULL,
    idempotency_key     TEXT NOT NULL,
    request_hash        CHAR(64) NOT NULL CHECK (request_hash ~ '^[0-9a-f]{64}$'),
    operation_id        UUID REFERENCES operation_requests(id),
    response_status     INTEGER CHECK (response_status BETWEEN 200 AND 599),
    response_body       JSONB,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at          TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (scope, idempotency_key)
);

CREATE TABLE audit_events (
    id                 UUID PRIMARY KEY,
    occurred_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    actor_id           TEXT NOT NULL,
    actor_role         TEXT NOT NULL,
    action             TEXT NOT NULL,
    aggregate_type     TEXT NOT NULL,
    aggregate_id       UUID NOT NULL,
    before_revision    INTEGER,
    after_revision     INTEGER,
    reason_code        TEXT,
    trace_id           TEXT NOT NULL,
    payload            JSONB NOT NULL DEFAULT '{}'
);

CREATE TABLE outbox_events (
    sequence           BIGSERIAL PRIMARY KEY,
    event_id           UUID NOT NULL UNIQUE,
    event_type         TEXT NOT NULL,
    aggregate_type     TEXT NOT NULL,
    aggregate_id       UUID NOT NULL,
    aggregate_revision INTEGER,
    trace_id           TEXT NOT NULL,
    occurred_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    payload            JSONB NOT NULL,
    published_at       TIMESTAMPTZ,
    publish_attempts   INTEGER NOT NULL DEFAULT 0 CHECK (publish_attempts >= 0),
    last_error_code    TEXT
);

CREATE INDEX ix_source_revisions_series ON source_revisions(series_id, revision DESC);
CREATE INDEX ix_evidence_source_offsets ON evidence_spans(source_revision_id, start_offset);
CREATE INDEX ix_episode_revisions_episode ON episode_revisions(episode_id, revision DESC);
CREATE INDEX ix_scene_revisions_episode ON scene_revisions(episode_revision_id);
CREATE INDEX ix_entity_revisions_series_type ON entity_revisions(series_id, entity_type);
CREATE INDEX ix_context_revisions_scope ON context_revisions(scope_type, scope_id, revision DESC);
CREATE INDEX ix_provider_profiles_health ON provider_profiles(provider, enabled, health);
CREATE INDEX ix_provider_capabilities_alias ON provider_capability_snapshots(capability_alias, status, effective_at DESC);
CREATE INDEX ix_model_routes_active ON model_routes(capability_alias, priority) WHERE status = 'ACTIVE';
CREATE INDEX ix_assets_series_type ON assets(series_id, asset_type);
CREATE INDEX ix_asset_versions_status ON asset_versions(asset_id, status);
CREATE INDEX ix_shot_specs_shot ON shot_spec_revisions(shot_id, revision DESC);
CREATE INDEX ix_shot_specs_freshness ON shot_spec_revisions(freshness, lifecycle_state);
CREATE INDEX ix_runs_shot_state ON generation_runs(shot_spec_revision_id, state);
CREATE INDEX ix_runs_temporal_workflow ON generation_runs(temporal_workflow_id);
CREATE INDEX ix_attempts_run_state ON generation_attempts(generation_run_id, state);
CREATE INDEX ix_provider_jobs_reconcile ON provider_jobs(state, next_poll_at)
    WHERE state IN ('QUEUED', 'RUNNING', 'UNKNOWN');
CREATE INDEX ix_provider_jobs_upstream ON provider_jobs(provider_profile_id, upstream_task_id);
CREATE INDEX ix_cost_ledger_job ON cost_ledger(provider_job_id, created_at);
CREATE INDEX ix_artifacts_status_created ON artifacts(status, created_at);
CREATE INDEX ix_qc_reports_state ON qc_reports(state, created_at);
CREATE INDEX ix_review_tasks_open ON review_tasks(state, assigned_role) WHERE state = 'OPEN';
CREATE INDEX ix_dependencies_producer ON revision_dependencies(producer_type, producer_revision_id);
CREATE INDEX ix_dependencies_consumer ON revision_dependencies(consumer_type, consumer_revision_id);
CREATE INDEX ix_freshness_impacts_affected ON freshness_impacts(affected_type, affected_revision_id, state);
CREATE INDEX ix_operations_aggregate ON operation_requests(aggregate_type, aggregate_id, created_at DESC);
CREATE INDEX ix_idempotency_expiry ON idempotency_records(expires_at);
CREATE INDEX ix_audit_aggregate_time ON audit_events(aggregate_type, aggregate_id, occurred_at DESC);
CREATE INDEX ix_outbox_unpublished ON outbox_events(sequence) WHERE published_at IS NULL;

COMMENT ON SCHEMA video_pipeline IS
    'FLO-108 AI video production control-plane truth; separate from the legacy Vibe Forge SQLite application';
COMMENT ON TABLE generation_runs IS
    'One creative generation. Infrastructure recovery reuses the same run; controlled creative retry creates a new run.';
COMMENT ON TABLE revision_dependencies IS
    'Explicit dependency graph used for deterministic stale impact propagation; no hidden database triggers.';
COMMENT ON TABLE outbox_events IS
    'Transactional integration events. BIGSERIAL provides concurrency-safe ordering without MAX(seq)+1.';
